# Generated by Django 5.2.8 on 2026-04-15 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(choices=[('mocoa', 'Mocoa'), ('sibundoy', 'Sibundoy'), ('puerto_asis', 'Puerto Asis'), ('hormiga', 'Hormiga'), ('orito', 'Orito'), ('leguizamo', 'Leguizamo'), ('dorada', 'Dorada'), ('villagarzon', 'Villagarzon')], max_length=50)),
                ('fecha_informe', models.DateTimeField()),
                ('tipo_actividad', models.CharField(max_length=100)),
                ('nombre', models.TextField()),
                ('fecha_actividad', models.DateTimeField()),
                ('lugar', models.CharField(max_length=255)),
                ('cupo', models.IntegerField()),
                ('asociados', models.IntegerField()),
                ('acompanantes', models.IntegerField()),
                ('facilitador', models.TextField(blank=True)),
                ('entidad', models.TextField(blank=True)),
                ('programa', models.TextField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ganador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_premio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('identificacion', models.CharField(max_length=50)),
                ('es_colaborador', models.BooleanField(default=False)),
                ('es_directivo', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='registrar_eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('proyectado', 'Proyectado'), ('ejecutado', 'Ejecutado')], max_length=20)),
                ('refrigerio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('almuerzo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('publicidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sonido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('video', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('premiacion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('imprevistos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('otros', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='registrar_eventos.evento')),
            ],
        ),
    ]
