# Generated by Django 5.2.8 on 2026-04-16 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(max_length=100)),
                ('fecha_informe', models.DateTimeField()),
                ('tipo_actividad', models.CharField(max_length=100)),
                ('nombre_actividad', models.TextField()),
                ('fecha_actividad', models.DateTimeField()),
                ('lugar_actividad', models.CharField(max_length=255)),
                ('cupo_participantes', models.IntegerField()),
                ('asociados_participantes', models.IntegerField()),
                ('acompanantes_participantes', models.IntegerField()),
                ('facilitador', models.TextField(blank=True)),
                ('entidad_aliada', models.TextField(blank=True)),
                ('programa_desarrollo', models.TextField(blank=True)),
                ('descripcion_ejecucion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_participante', models.CharField(choices=[('colaborador', 'Colaborador'), ('directivo', 'Directivo')], max_length=20)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('identificacion', models.CharField(max_length=50)),
                ('agencia', models.CharField(max_length=100)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='registrar_eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Premiacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('identificacion', models.CharField(max_length=50)),
                ('agencia', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('infantil', 'Infantil'), ('juvenil', 'Juvenil'), ('libre', 'Libre')], max_length=20)),
                ('puesto_numero', models.IntegerField()),
                ('valor_premio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premiaciones', to='registrar_eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('proyectado', 'Proyectado'), ('ejecutado', 'Ejecutado')], max_length=20)),
                ('refrigerio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('almuerzo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('publicidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sonido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('video', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('premiacion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('imprevistos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('otros', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_proyecto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_presupuesto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='registrar_eventos.evento')),
            ],
        ),
    ]
