# Generated by Django 5.2.8 on 2026-04-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='identificacion',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
