# Generated by Django 5.2.8 on 2026-04-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_actividad',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_informe',
            field=models.DateField(),
        ),
    ]
