# Generated by Django 5.2.8 on 2026-04-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_eventos', '0002_alter_participante_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='almuerzo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='imprevistos',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='otros',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='premiacion',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='publicidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='refrigerio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='sonido',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='video',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
