# Generated by Django 5.2.8 on 2026-04-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_eventos', '0002_alter_evento_fecha_actividad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descripcion_ejecucion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='entidad_aliada',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='facilitador',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='programa_desarrollo',
            field=models.TextField(),
        ),
    ]
