# Generated by Django 5.2.8 on 2026-04-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_eventos', '0003_alter_presupuesto_almuerzo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiacion',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
    ]
