# Generated by Django 5.2.8 on 2026-04-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_eventos', '0003_alter_evento_descripcion_ejecucion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='evento',
        ),
        migrations.AddField(
            model_name='evento',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, related_name='eventos_colaborador', to='registrar_eventos.participante'),
        ),
        migrations.AddField(
            model_name='evento',
            name='directivos',
            field=models.ManyToManyField(blank=True, related_name='eventos_directivo', to='registrar_eventos.participante'),
        ),
    ]
