# Generated by Django 5.2.8 on 2026-04-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_eventos', '0004_remove_participante_evento_evento_colaboradores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='tipo_participante',
            field=models.CharField(max_length=100),
        ),
    ]
