# Generated by Django 5.2.8 on 2026-04-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_eventos', '0005_alter_presupuesto_almuerzo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiacion',
            name='valor_premio',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='almuerzo',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='imprevistos',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='otros',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='premiacion',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='publicidad',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='refrigerio',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='sonido',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='total_presupuesto',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='valor_proyecto',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='video',
            field=models.BigIntegerField(),
        ),
    ]
